/**
 * English translation dictionary
 */
const en = {
  // ── Common ──
  common: {
    loading: "Loading...",
    error: "Error",
    confirm: "Confirm",
    cancel: "Cancel",
    back: "Back",
    save: "Save",
    close: "Close",
    retry: "Retry",
    seconds: "sec",
    times: "times",
  },

  // ── Navigation ──
  nav: {
    features: "Features",
    showcase: "Showcase",
    getAccess: "Get Access",
    platform: "AI Video Creation Platform",
  },

  // ── Landing Page ──
  landing: {
    badge: "AI Multi-Agent Powered · Fully Automated Video Pipeline",
    heroTitle1: "Turn Ideas into",
    heroTitle2: "Viral Hits",
    heroHighlight: "Automatically",
    heroDesc:
      "AutoViralVid deploys Director, Writer, and Editor AI Agents working together to automatically generate high-converting marketing videos from script to final cut.",
    startFree: "Start Free Experience",
    // Features
    featMultiAgent: "Multi-Agent Collaboration",
    featMultiAgentDesc:
      "Director, Writer, and Editor AI Agents work in sync to ensure narrative consistency and visual coherence.",
    featOneClick: "One-Click Generation",
    featOneClickDesc:
      "Enter a topic or link, AI auto-completes asset search, voiceover synthesis, and subtitle alignment.",
    featRealtime: "Real-Time Editing",
    featRealtimeDesc:
      "Not satisfied with AI editing? Jump into the timeline editor to adjust clips, change styles, or regenerate.",
    featDigitalHuman: "Digital Human Presenter",
    featDigitalHumanDesc:
      "Upload a portrait photo + audio, AI drives a digital human to speak and sell, with voice cloning support.",
    featSectionTitle: "Workflow of the Future",
    featSectionDesc:
      "Replace tedious manual editing with an intelligent crew that understands pacing, narrative, and visual engagement.",
    // Showcase
    showcaseEcommerce: "E-Commerce",
    showcaseBrand: "Brand Story",
    showcaseKnowledge: "Education",
    showcaseTagHot: "Hot",
    showcaseTagPro: "Pro",
    showcaseTagEdu: "Edu",
    showcaseSectionTitle: "Made with AutoViralVid",
    showcaseSectionDesc:
      "See what our autonomous agents can create in minutes.",
    showcaseAutoGenerated: "AI Generated · One Click",
    // CTA
    ctaTitle: "Ready to transform your workflow?",
    ctaDesc:
      "Join the waiting list today and get 50% off your first month.",
    ctaButton: "Get Early Access",
    // Footer
    footerCopyright: "© 2026 AutoViralVid. All rights reserved.",
    // Auth modal
    authCreateAccount: "Create Account",
    authWelcomeBack: "Welcome Back",
    authSignUpDesc: "Sign up to start creating videos",
    authSignInDesc: "Sign in to your account",
    authEmail: "Email",
    authPassword: "Password",
    authSignUp: "Create Account",
    authSignIn: "Sign In",
    authSwitchToSignIn: "Already have an account? Sign In",
    authSwitchToSignUp: "Don't have an account? Sign Up",
    authSignUpSuccessLoginFailed:
      "Registration succeeded but login failed. Please try signing in.",
    authInvalidCredentials: "Invalid email or password.",
    authUnexpectedError:
      "An unexpected error occurred. Please try again.",
    authOrContinueWith: "Or continue with",
    authGoogleLogin: "Sign in with Google",
  },

  // ── Template Gallery ──
  gallery: {
    title: "Choose a Template, Start Creating",
    subtitle:
      "Covering e-commerce, brand, content and more video scenarios",
    blankProject: "Blank Project",
    blankProjectDesc: "Free creation without preset templates",
    templateCount: "templates",
    catEcommerce: "E-Commerce",
    catBrand: "Brand Marketing",
    catContent: "Content Creation",
    tplProductAd: "Product Ad",
    tplBeautyReview: "Beauty Review",
    tplFashionStyle: "Fashion Style",
    tplFoodShowcase: "Food Showcase",
    tplTechUnbox: "Tech Unbox",
    tplHomeLiving: "Home & Living",
    tplBrandStory: "Brand Story",
    tplDigitalHuman: "Digital Human",
    tplKnowledgeEdu: "Knowledge & Edu",
    tplFunnySkit: "Comedy Skit",
    tplTravelVlog: "Travel Vlog",
    tplTutorial: "Tutorial Video",
    tplProductAdDesc:
      "Fast-paced, high-contrast commercial short videos for social media promotion.",
    tplBeautyReviewDesc:
      "Product close-ups + effect showcase for beauty and skincare promotion.",
    tplFashionStyleDesc:
      "Multi-angle display + styling recommendations for clothing brand promotion.",
    tplFoodShowcaseDesc:
      "Food close-ups + cooking process + tasting reactions for F&B promotion.",
    tplTechUnboxDesc:
      "Unboxing + feature demo + spec comparison for digital product reviews.",
    tplHomeLivingDesc:
      "Scene-based display + usage experience for home & living products.",
    tplBrandStoryDesc:
      "Strong narrative, warm-toned brand promotion to build emotional connection.",
    tplDigitalHumanDesc:
      "Upload portrait + audio, AI drives digital human to speak with voice cloning.",
    tplKnowledgeEduDesc:
      "Problem-driven + visual explanation for educational knowledge content.",
    tplFunnySkitDesc:
      "Daily twist + creative expression for entertainment comedy content.",
    tplTravelVlogDesc:
      "Scenery + cultural experience + narrative for travel life records.",
    tplTutorialDesc:
      "Step-by-step breakdown + annotation animations + progress indicator for software, knowledge, and product tutorials.",
    tagHot: "Hot",
    tagEcommerce: "E-com",
    tagPro: "Pro",
    tagDigitalHuman: "Avatar",
    tagContent: "Content",
  },

  // ── Project Form ──
  form: {
    videoConfig: "Video Config",
    digitalHumanMode: "Digital Human",
    aiGenMode: "AI Generate",
    template: "Template",
    themeDesc: "Theme Description",
    themePlaceholder:
      "Describe your video theme, e.g.: Summer sunscreen spray review...",
    imageLabel: "Product Image",
    imageDigitalHumanLabel: "Portrait Image",
    imagePlaceholder: "Product image URL",
    imageDigitalHumanPlaceholder: "Digital human portrait URL",
    audioFile: "Audio File",
    audioPlaceholder: "Audio file URL",
    audioHint: "Supports up to 30-min audio, auto-segmented synthesis",
    voiceMode: "Voice Mode",
    voiceOriginal: "Original Audio",
    voiceClone: "Clone + Text",
    synthesisText: "Synthesis Text",
    synthesisPlaceholder: "Text for cloned voice to speak...",
    motionDesc: "Motion Description",
    motionPlaceholder:
      "Model is doing product demo, live streaming e-commerce",
    style: "Style",
    duration: "Duration",
    screen: "Screen",
    vertical: "Portrait",
    horizontal: "Landscape",
    square: "Square",
    generating: "Generating...",
    generateDigitalHuman: "Generate Digital Human",
    startGenerate: "Start Generate",
    needImageUrl: "Please provide a digital human portrait image URL",
    needAudioUrl: "Please provide an audio file URL",
    uploadFailed: "Upload failed",
    uploadNetworkError: "Upload network error",
    getUploadUrlFailed: "Failed to get upload URL",
    uploaded: "Uploaded",
    selectLocalFile: "Select local file to upload",
    fileTooLarge: "File must not exceed",
    currentSize: "current",
    unsupportedFormat: "Unsupported format",
    supported: "Supported",
    imageUploadFailed: "Image upload failed",
    audioUploadFailed: "Audio upload failed",
    imageFileLabel: "Image",
    audioFileLabel: "Audio",
    styleModernMinimal: "Modern Minimal",
    styleChinese: "Chinese Style",
    styleJapanese: "Japanese Fresh",
    styleWestern: "Western Fashion",
    styleCyberpunk: "Cyberpunk",
    styleRetro: "Retro Film",
    stylePremium: "Premium",
    styleNatural: "Natural Documentary",
  },

  // ── Sidebar ──
  sidebar: {
    backToTemplates: "Back to templates",
    newProject: "New Project",
    historyProjects: "History",
    loading: "Loading...",
    noHistory: "No history yet",
    guide: "User Guide",
    signOut: "Sign Out",
  },

  historyPage: {
    title: "Video History",
    subtitle: "Review finished videos, inspect async progress, and reopen past runs.",
    refresh: "Refresh",
    empty: "No video runs yet",
    detail: "Run Detail",
    continueProject: "Open in Studio",
    openVideo: "Open Video",
    status: "Project Status",
    tasks: "tasks",
    createdAt: "Created",
    sessionStatus: "Session",
    taskBreakdown: "Async Task Breakdown",
    asyncStatusHint: "Persisted segment tasks continue running even after the page is closed.",
    finalVideo: "Final Video",
    finalVideoHint: "When synthesis is done, the final mp4 is restored here and in history.",
    noVideoYet: "The final video is not ready yet. This run will continue in the background.",
    searchPlaceholder: "Search by theme, run ID, or status",
    filterAll: "All",
    filterRunning: "Running",
    filterCompleted: "Completed",
    filterFailed: "Failed",
    noMatches: "No runs match the current filter",
  },


  // ── Workspace ──
  workspace: {
    idleTitle: "Fill in the config on the left to start",
    idleDesc:
      "AI will auto-generate storyboard, scene images and video clips, composing the final work",
    step01: "Configure",
    step02: "AI Generate",
    step03: "Export Video",
    errorTitle: "Generation Error",
    errorDesc: "Please check parameters and retry",
  },

  // ── Quota ──
  quota: {
    unlimited: "Unlimited Quota",
    exhausted: "Quota exhausted — Upgrade plan",
  },

  // ── Settings ──
  settings: {
    title: "Account Settings",
    profile: "Profile",
    userId: "User ID",
    email: "Email",
    security: "Security",
    changePassword: "Change Password",
    comingSoon: "Coming Soon",
    legal: "Legal",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    signOut: "Sign Out",
    loginRequired: "Please sign in first",
    backToHome: "Back to Home",
  },

  // ── Error Pages ──
  errorPage: {
    title: "Something Went Wrong",
    desc: "An error occurred while loading the page. Please try refreshing. Contact support if the issue persists.",
    errorCode: "Error Code",
    reload: "Reload",
  },
  notFound: {
    title: "Page Not Found",
    desc: "The page you visited has been removed or the URL is incorrect.",
    backToHome: "Back to Home",
  },
  globalError: {
    title: "System Error",
    desc: "A critical error occurred. Please refresh the page and try again.",
    refresh: "Refresh Page",
  },

  // ── Language switcher ──
  language: {
    zh: "中文",
    en: "English",
    switchLang: "Language",
  },
} as const;

export default en;
