/**
 * Chinese (Simplified) translation dictionary
 */
const zh = {
  // ── Common ──
  common: {
    loading: "加载中...",
    error: "出错了",
    confirm: "确认",
    cancel: "取消",
    back: "返回",
    save: "保存",
    close: "关闭",
    retry: "重试",
    seconds: "秒",
    times: "次",
  },

  // ── Navigation ──
  nav: {
    features: "功能",
    showcase: "案例",
    getAccess: "开始使用",
    platform: "智能视频创作平台",
  },

  // ── Landing Page ──
  landing: {
    badge: "AI多Agent驱动 · 全自动视频生产线",
    heroTitle1: "将创意变为",
    heroTitle2: "爆款内容",
    heroHighlight: "自动化",
    heroDesc:
      "AutoViralVid 部署导演、编剧、剪辑师 AI Agent 协同工作，从脚本到成片，自动生成高转化营销短视频。",
    startFree: "开始免费体验",
    // Features
    featMultiAgent: "多Agent协作",
    featMultiAgentDesc:
      "导演、编剧、剪辑师 AI Agent 协同工作，确保叙事一致性与视觉连贯性。",
    featOneClick: "一键生成",
    featOneClickDesc:
      "输入主题或链接，AI 自动完成素材检索、配音合成、字幕对齐。",
    featRealtime: "实时编辑",
    featRealtimeDesc:
      "不满意 AI 的剪辑？跳入时间线编辑器，调整片段、更换风格、重新生成。",
    featDigitalHuman: "数字人口播",
    featDigitalHumanDesc:
      "上传形象照+音频，AI 驱动数字人说话带货，支持声音克隆。",
    featSectionTitle: "未来工作流",
    featSectionDesc:
      "用智能 AI 团队替代繁琐的手动剪辑，它们能理解节奏、叙事和视觉吸引力。",
    // Showcase
    showcaseEcommerce: "电商带货",
    showcaseBrand: "品牌故事",
    showcaseKnowledge: "知识科普",
    showcaseTagHot: "爆款",
    showcaseTagPro: "专业",
    showcaseTagEdu: "教育",
    showcaseSectionTitle: "AutoViralVid 作品",
    showcaseSectionDesc: "看看我们的自动化 Agent 能在几分钟内创造什么。",
    showcaseAutoGenerated: "AI 自动生成 · 一键完成",
    // CTA
    ctaTitle: "准备好改变您的工作流了吗？",
    ctaDesc: "立即加入等待名单，首月享 50% 优惠。",
    ctaButton: "获取早期访问权限",
    // Footer
    footerCopyright: "© 2026 AutoViralVid. 保留所有权利。",
    // Auth modal
    authCreateAccount: "创建账户",
    authWelcomeBack: "欢迎回来",
    authSignUpDesc: "注册开始创作视频",
    authSignInDesc: "登录您的账户",
    authEmail: "邮箱",
    authPassword: "密码",
    authSignUp: "创建账户",
    authSignIn: "登录",
    authSwitchToSignIn: "已有账户？登录",
    authSwitchToSignUp: "没有账户？注册",
    authSignUpSuccessLoginFailed:
      "注册成功但登录失败，请重新登录。",
    authInvalidCredentials: "邮箱或密码无效。",
    authUnexpectedError: "发生意外错误，请重试。",
    authOrContinueWith: "或使用以下方式继续",
    authGoogleLogin: "使用 Google 登录",
  },

  // ── Template Gallery ──
  gallery: {
    title: "选择模板，开启创作之旅",
    subtitle: "覆盖电商、品牌、内容等多种短视频场景",
    blankProject: "空白项目",
    blankProjectDesc: "自由创作，不使用预设模板",
    templateCount: "个模板",
    catEcommerce: "电商带货",
    catBrand: "品牌营销",
    catContent: "内容创作",
    tplProductAd: "爆款产品广告",
    tplBeautyReview: "美妆种草",
    tplFashionStyle: "服饰穿搭",
    tplFoodShowcase: "美食探店",
    tplTechUnbox: "3C数码开箱",
    tplHomeLiving: "家居好物",
    tplBrandStory: "温馨品牌故事",
    tplDigitalHuman: "数字人口播",
    tplKnowledgeEdu: "知识科普",
    tplFunnySkit: "搞笑段子",
    tplTravelVlog: "旅行Vlog",
    tplTutorial: "教程视频",
    tplProductAdDesc: "快节奏、高对比度的商业短视频，适合社交媒体推广。",
    tplBeautyReviewDesc: "产品特写+使用效果展示，适合美妆护肤品推广种草。",
    tplFashionStyleDesc: "多角度展示+搭配推荐，适合服装鞋包品牌宣传。",
    tplFoodShowcaseDesc: "美食特写+制作过程+品尝反应，适合餐饮食品推广。",
    tplTechUnboxDesc: "开箱展示+功能演示+参数对比，适合数码产品评测。",
    tplHomeLivingDesc: "场景化展示+使用体验+氛围营造，适合家居家装。",
    tplBrandStoryDesc: "叙事感强、色调柔和的品牌宣传，建立品牌情感连接。",
    tplDigitalHumanDesc:
      "上传形象图+音频，AI驱动数字人说话带货，支持声音克隆。",
    tplKnowledgeEduDesc: "问题驱动+图文讲解+案例演示，适合教育知识类内容。",
    tplFunnySkitDesc: "日常反转+创意表达+节奏把控，适合娱乐搞笑内容。",
    tplTravelVlogDesc: "风景展示+人文体验+氛围叙事，适合旅行生活记录。",
    tplTutorialDesc: "步骤分解+标注动画+进度指示，适合软件操作、知识讲解、产品使用教程。",
    tagHot: "热门",
    tagEcommerce: "电商",
    tagPro: "专业",
    tagDigitalHuman: "数字人",
    tagContent: "内容",
  },

  // ── Project Form ──
  form: {
    videoConfig: "视频配置",
    digitalHumanMode: "数字人口播",
    aiGenMode: "AI 生成",
    template: "模板",
    themeDesc: "主题描述",
    themePlaceholder: "描述视频主题，例如：夏日防晒喷雾评测…",
    imageLabel: "素材图片",
    imageDigitalHumanLabel: "形象图片",
    imagePlaceholder: "产品图片链接 (URL)",
    imageDigitalHumanPlaceholder: "数字人半身照链接 (URL)",
    audioFile: "音频文件",
    audioPlaceholder: "音频文件链接 (URL)",
    audioHint: "支持 30 分钟长音频，自动分段合成",
    voiceMode: "声音模式",
    voiceOriginal: "原声音频",
    voiceClone: "克隆+文本",
    synthesisText: "合成文本",
    synthesisPlaceholder: "克隆声音要说的文本…",
    motionDesc: "动作描述",
    motionPlaceholder: "模特正在做产品展示，进行电商直播带货",
    style: "风格",
    duration: "时长",
    screen: "画面",
    vertical: "竖屏",
    horizontal: "横屏",
    square: "方形",
    generating: "生成中…",
    generateDigitalHuman: "生成数字人视频",
    startGenerate: "开始生成",
    needImageUrl: "请提供数字人形象图片 URL",
    needAudioUrl: "请提供音频文件 URL",
    uploadFailed: "上传失败",
    uploadNetworkError: "上传网络错误",
    getUploadUrlFailed: "获取上传链接失败",
    uploaded: "已上传",
    selectLocalFile: "选择本地文件上传",
    fileTooLarge: "文件不能超过",
    currentSize: "当前",
    unsupportedFormat: "不支持的格式",
    supported: "支持",
    imageUploadFailed: "图片上传失败",
    audioUploadFailed: "音频上传失败",
    imageFileLabel: "图片",
    audioFileLabel: "音频",
    styleModernMinimal: "现代简约",
    styleChinese: "中国风",
    styleJapanese: "日系清新",
    styleWestern: "欧美时尚",
    styleCyberpunk: "赛博朋克",
    styleRetro: "复古胶片",
    stylePremium: "高级质感",
    styleNatural: "自然纪实",
  },

  // ── Sidebar ──
  sidebar: {
    backToTemplates: "返回模板",
    newProject: "新项目",
    historyProjects: "历史项目",
    loading: "加载中...",
    noHistory: "暂无历史记录",
    guide: "使用指引",
    signOut: "退出登录",
  },

  // ── Workspace ──
  workspace: {
    idleTitle: "填写左侧配置，开始创作",
    idleDesc:
      "AI 将自动生成分镜脚本、场景图片和视频片段，最终合成完整作品",
    step01: "配置参数",
    step02: "AI 生成",
    step03: "导出视频",
    errorTitle: "生成出错",
    errorDesc: "请检查参数后重试",
  },

  // ── Quota ──
  quota: {
    unlimited: "无限配额",
    exhausted: "配额已用完 — 升级方案",
  },

  // ── Settings ──
  settings: {
    title: "账户设置",
    profile: "个人信息",
    userId: "用户 ID",
    email: "邮箱",
    security: "安全",
    changePassword: "修改密码",
    comingSoon: "即将推出",
    legal: "法律条款",
    termsOfService: "服务条款",
    privacyPolicy: "隐私政策",
    signOut: "退出登录",
    loginRequired: "请先登录",
    backToHome: "返回首页",
  },

  // ── Error Pages ──
  errorPage: {
    title: "出了点问题",
    desc: "页面加载时遇到错误。请尝试刷新，如果问题持续请联系技术支持。",
    errorCode: "错误代码",
    reload: "重新加载",
  },
  notFound: {
    title: "页面不存在",
    desc: "您访问的页面已被移除或地址有误。",
    backToHome: "返回首页",
  },
  globalError: {
    title: "系统错误",
    desc: "应用出现严重错误，请刷新页面重试。",
    refresh: "刷新页面",
  },

  // ── Language switcher ──
  language: {
    zh: "中文",
    en: "English",
    switchLang: "切换语言",
  },
} as const;

export default zh;
